name: build

on:
  workflow_dispatch:
    inputs:
      macos_arm64:
        description: "Build for MacOS arm64"
        required: true
        default: true
        type: boolean

      macos_x64:
        description: "Build for MacOS x64"
        required: true
        default: true
        type: boolean

      linux_x64:
        description: "Build for Linux x64"
        required: true
        default: true
        type: boolean

      windows_x64:
        description: "Build for Windows x64"
        required: true
        default: true
        type: boolean

jobs:
  bundle:
    strategy:
      matrix:
        os: [ macos-latest, macos-13, ubuntu-latest, windows-latest ]
        exclude:
          - os: ${{ !inputs.macos_arm64 && 'macos-latest' }}
          - os: ${{ !inputs.macos_x64 && 'macos-13' }}
          - os: ${{ !inputs.linux_x64 && 'ubuntu-latest' }}
          - os: ${{ !inputs.windows_x64 && 'windows-latest' }}
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Dependencies for Linux x64
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get -y install ant git gcc cmake bison flex pkg-config
          sudo apt-get -y install libx11-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '21'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: 'JetBrains/jcef'

      - name: Build for Linux x64
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          ./jb/tools/linux/build.sh all x86_64

      - name: Build for MacOS x64
        if: ${{ matrix.os == 'macos-13' }}
        run: |
          ./jb/tools/mac/build.sh all x86_64

      - name: Build for MacOS arm64
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          ./jb/tools/mac/build.sh all arm64

      - name: Build
        shell: bash
        run: |
          echo ""
          echo "-------------------"
          echo " DIRECTORY LISTING"
          echo "-------------------"
          echo "ROOT:"
          ls -1
          echo "OUT:"
          ls -1 out
          echo "-------------------"
          echo ""

      - name: Upload linux64-packages
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: linux64
          path: |
            ./*.tar.gz
            ./out/linux64
